export const concepts = [
  ['/concepts/error-handling', 'Error handling'],
  ['/concepts/messages', 'Status messages'],
  ['/concepts/client-validation', 'Client validation'],
  ['/concepts/submit-behavior', 'Submit behavior'],
  ['/concepts/tainted', 'Tainted fields'],
  ['/concepts/events', 'Events'],
  ['/concepts/timers', 'Loading timers'],
  ['/concepts/files', 'File uploads'],
  ['/concepts/nested-data', 'Nested data'],
  ['/concepts/multiple-forms', 'Multiple forms'],
  ['/concepts/proxy-objects', 'Proxy objects'],
  ['/concepts/snapshots', 'Snapshots'],
  ['/concepts/spa', 'Single-page apps'],
  ['/concepts/enhance', 'use:enhance'],
];
